        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 15:53:16 2013
        MODULE PARSEWORDSTATUS__genmod
          INTERFACE 
            SUBROUTINE PARSEWORDSTATUS(INPUT,WORDID,WORDSTATUS)
              CHARACTER(LEN=10) :: INPUT
              INTEGER(KIND=4) :: WORDID
              INTEGER(KIND=1) :: WORDSTATUS
            END SUBROUTINE PARSEWORDSTATUS
          END INTERFACE 
        END MODULE PARSEWORDSTATUS__genmod
