        !COMPILER-GENERATED INTERFACE MODULE: Sat Jun 22 15:53:16 2013
        MODULE PARSEUSER__genmod
          INTERFACE 
            SUBROUTINE PARSEUSER(INPUT,USERID,LASTDAY)
              CHARACTER(LEN=15000) :: INPUT
              INTEGER(KIND=4) :: USERID
              INTEGER(KIND=1) :: LASTDAY
            END SUBROUTINE PARSEUSER
          END INTERFACE 
        END MODULE PARSEUSER__genmod
