        !COMPILER-GENERATED INTERFACE MODULE: Mon Jun 24 23:16:01 2013
        MODULE TIME2013__genmod
          INTERFACE 
            SUBROUTINE TIME2013(DAY,MONTH,TIME)
              INTEGER(KIND=1) :: DAY
              INTEGER(KIND=1) :: MONTH
              INTEGER(KIND=2) :: TIME
            END SUBROUTINE TIME2013
          END INTERFACE 
        END MODULE TIME2013__genmod
